name: Test
on: [pull_request]
jobs:
  build:
    name: CI Test
    runs-on: ubuntu-20.04
    steps:
    - name: Set up Go 1.20
      uses: actions/setup-go@v2
      with:
        go-version: 1.20
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: |
        go build -o eseparser bin/*.go

    - name: Test
      shell: bash
      if: always()
      run: |
        go test -v ./...

    - name: Store Artifacts
      shell: bash
      if: ${{ ! success() }}
      run: |
        go test -v -update

    - uses: actions/upload-artifact@master
      if: ${{ ! success() }}
      with:
        name: fixtures
        path: fixtures
